---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: flipflop
spec:
  title: Flip Flop
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/nginx
  ports:
    - serviceName: "nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://nginx"
