apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: flip
spec:
  teamId: "flip"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    flip:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: flip  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
